### ISSUE TITLE
运行python generate_static_files.py 命令 ，希望生成文件报错，报错

### ISSUE THREAD

**Issue by victorsheng** [lijin-THU/notes-python#9]
运行python generate_static_files.py 命令 ，希望生成文件报错，报错：

bogon:notes-python wingjoy$ python generate_static_files.py
  File "generate_static_files.py", line 71
    print file_name
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print file_name)?

**Comment by lijin-THU** [comment]
请用Python 2运行
